{% set name = "CacheControl" %}
{% set version = "0.12.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b5d0c98f7ee9f02e2d5a85af98b9a76c0a2c73c972c142291f823a0ed2eb7a78

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - doesitcache = cachecontrol._cmd:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests
    - msgpack-python >=0.5.2

test:
  requires:
    - pip
  imports:
    - cachecontrol
  commands:
    - pip check
    - doesitcache --help

about:
  home: https://github.com/ionrock/cachecontrol
  license: Apache-2.0
  license_family: Apache
  license_file: Apache-2.0.txt
  summary: The httplib2 caching algorithms packaged up for use with requests
  description: |
    CacheControl is a port of the caching algorithms in httplib2 for use with
    requests session object.
    It was written because httplib2's better support for caching is often
    mitigated by its lack of threadsafety. The same is true of requests
    in terms of caching.
  doc_url: http://cachecontrol.readthedocs.io/
  dev_url: https://github.com/ionrock/cachecontrol

extra:
  recipe-maintainers:
    - djsutherland
    - ocefpaf
