travis:
  secure:
    BINSTAR_TOKEN: kDagWzjWGxMyfOKZO6CHL4FJvGwpSH16vPBEPRdbn09AEIwW33QPrMS0uYCAIsl7mtw1sPv1Fntnj9AcpPCbA127rU4wEa844933z061iOclyHgcinQWdcAkTHicMIqRVolR6scR2MJHqo8CZyzLOGJzA381WG0w5Cwl+SDyRgNZzw+YRCRW9RBsgWgGAoO9Vuq8urLyzhxOEkxo3d1R8iZmI8V0JuugbnoD/bB1T2ij0FRG/HYWVdAcj+R/cdwnYqeGOVFNABtIwMGC9sDfgO82QVyA8OgvHNZ8hYsgwPr63ba1UsntLRIF1vJ/lyP8SxdWFeTYIM1YuFUpZTMd93dM0OoH3OoM+p1Chy4XQBX3f+CePZYwwk2V0jWUqMw86RNK3gjTeb+AS4JzWmbmSpzYYzw1qYWchwBYPZ1uvyyqEVFwd/vke0ISFKd/Hb0/y4XSSu8mfpm2yHAVENNv0IM1h909eFBCtLoc5xRwe2FCRlipMzft8ALRTVr7v3eeTaVMfJ35czybfxUQyAa8hPtQZZhnNl6FRe0Vn/K8kyDlebcwD8qECK9Rg556oHehB0SzZfHbKIzXPAqEOsEYOVHwQvn0eB1qkiFP8CRvruZimgeZdksEMMp1DHHEKERrlgXGj8qzTi22eVfigPnweQ5ZyZ3g2GK+UZCGKe/fB98=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
